version: "3.8"

services:
  pusdipaiserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: pusdipaiserver
    container_name: pusdipaiserver
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
